# Generated by Django 4.1.4 on 2023-01-08 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='שם הדלת', max_length=16, unique=True, verbose_name='שם הדלת:')),
                ('image', models.ImageField(blank=True, default='', help_text='תמונת הדלת', upload_to='images/door_types/', validators=[django.core.validators.validate_image_file_extension], verbose_name='סקיצה:')),
                ('height_calculation', models.DecimalField(decimal_places=1, default=0, help_text='הפחתה בגובה', max_digits=4, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='הפחתה בגובה:')),
                ('width_calculation', models.DecimalField(decimal_places=1, default=0, help_text='הפחתה ברוחב', max_digits=4, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='הפחתה ברוחב:')),
            ],
        ),
        migrations.CreateModel(
            name='EngravingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='דוגמת החריטה')),
                ('image', models.ImageField(default='', help_text='תמונת החריטה', upload_to='images/engraving_types', verbose_name='תמונת החריטה:')),
                ('compatible_doors', models.ManyToManyField(blank=True, help_text='דלתות מתאימות', to='main.doortype', verbose_name='סוגי דלתות תואמים:')),
            ],
        ),
        migrations.CreateModel(
            name='Hinge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='סוג הצירים', max_length=16, unique=True, verbose_name='')),
                ('compatible_doors', models.ManyToManyField(blank=True, help_text='דלתות מתאימות', to='main.doortype', verbose_name='סוגי דלתות תואמים:')),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='סוג המנעול', max_length=16, unique=True, verbose_name='סוג המנעול:')),
                ('compatible_doors', models.ManyToManyField(blank=True, help_text='דלתות מתאימות', to='main.doortype', verbose_name='סוגי דלתות תואמים:')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length='100', verbose_name='תיאור המבנה:')),
                ('image', models.ImageField(blank=True, help_text='תמונה', upload_to='images/structure', verbose_name='תמונה')),
                ('compatible_doors', models.ManyToManyField(blank=True, help_text='דלתות מתאימות', to='main.doortype', verbose_name='סוגי דלתות תואמים:')),
                ('compatible_engraving', models.ManyToManyField(blank=True, to='main.engravingtype', verbose_name='סוגי דלתות תואמים:')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='מספר הזמנה')),
                ('customer', models.CharField(max_length=16, verbose_name='לקוח')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='טלפון')),
                ('address', models.CharField(blank=True, max_length=64, verbose_name='כתובת')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('casing', models.CharField(choices=[('regular', 'רגילות'), ('adjustable', 'מתכוונן')], max_length=10, verbose_name='הלבשות')),
                ('comment', models.TextField(blank=True, max_length='100', verbose_name='הערות')),
                ('door_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doortype', verbose_name='סוג הדלתות')),
                ('engraving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.engravingtype', verbose_name='דוגמא')),
                ('hinges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hinge', verbose_name='צירים')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lock', verbose_name='מנעול')),
            ],
        ),
        migrations.CreateModel(
            name='DoorsGroupInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doortype', verbose_name='סוג הדלתות')),
                ('engraving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.engravingtype', verbose_name='דוגמא')),
                ('hinges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hinge', verbose_name='צירים')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lock', verbose_name='מנעול')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='DoorInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='גובה')),
                ('width', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='רוחב')),
                ('frame', models.DecimalField(blank=True, decimal_places=1, default='10', max_digits=3, verbose_name='משקוף')),
                ('direction', models.CharField(choices=[('R', 'R'), ('L', 'L')], max_length=4, verbose_name='')),
                ('comment', models.TextField(blank=True, max_length='1000', verbose_name='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doorsgroupinstance')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
