# Generated by Django 4.1.5 on 2023-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorinstance',
            name='comment',
            field=models.TextField(blank=True, help_text='הערות', max_length='1000', verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='doorinstance',
            name='direction',
            field=models.CharField(choices=[('R', 'R'), ('L', 'L')], max_length=4, verbose_name='כיוון'),
        ),
        migrations.AlterField(
            model_name='doorinstance',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='מספר דלתות'),
        ),
    ]
