# Generated by Django 4.1.5 on 2023-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_doorinstance_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorinstance',
            name='direction',
            field=models.CharField(choices=[(0, 'ימינה פנימה'), (1, 'שמאלה פנימה'), (2, 'ימינה החוצה'), (3, 'שמאלה החוצה')], max_length=4, verbose_name='כיוון'),
        ),
        migrations.DeleteModel(
            name='Covering',
        ),
    ]
