# Generated by Django 4.1.5 on 2023-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_doorinstance_direction_delete_covering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorinstance',
            name='direction',
            field=models.CharField(choices=[('0', 'ימינה פנימה'), ('1', 'שמאלה פנימה'), ('2', 'ימינה החוצה'), ('3', 'שמאלה החוצה')], max_length=2, verbose_name='כיוון'),
        ),
    ]
