# Generated by Django 4.1.5 on 2023-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_doorinstance_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorinstance',
            name='closer',
            field=models.BooleanField(default=False, verbose_name='מחזיר שמן'),
        ),
        migrations.AddField(
            model_name='doorinstance',
            name='mezuzah',
            field=models.BooleanField(default=False, verbose_name='מזוזה'),
        ),
        migrations.AlterField(
            model_name='doorinstance',
            name='direction',
            field=models.CharField(choices=[('ימינה פנימה', 'ימינה פנימה'), ('שמאלה פנימה', 'שמאלה פנימה'), ('ימינה החוצה', 'ימינה החוצה'), ('שמאלה החוצה', 'שמאלה החוצה')], max_length=16, verbose_name='כיוון'),
        ),
    ]
