# Generated by Django 4.1.5 on 2023-01-16 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_doorinstance_closer_alter_doorinstance_mezuzah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doortype',
            name='binder_calculation',
            field=models.DecimalField(decimal_places=1, default=0, help_text='הפחתה ברוחב', max_digits=4, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='רוחבן:'),
        ),
        migrations.AlterField(
            model_name='doortype',
            name='covering_into_width_calculation',
            field=models.DecimalField(decimal_places=1, default=0, help_text='הפחתה ברוחב', max_digits=4, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='הפחתה ברוחב:'),
        ),
        migrations.CreateModel(
            name='Covering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='')),
                ('image', models.ImageField(blank=True, default='', help_text='תמונה מעטה', upload_to='images/door_types/', validators=[django.core.validators.validate_image_file_extension], verbose_name='סקיצה:')),
                ('compatible_doors', models.ManyToManyField(blank=True, help_text='דלתות מתאימות', to='main.doortype', verbose_name='סוגי דלתות תואמים:')),
            ],
        ),
    ]
